
    const data=[
        {   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
            name:"Naresh",
            branch:"Computer Science and Engineering",
            semester:'First',
            from:"Gurugram",
        },
        {   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
            name:"Naresh",
            branch:"Computer Science and Engineering",
            semester:'First',
            from:"Gurugram",
        },
        {   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
        name:"Naresh",
        branch:"Computer Science and Engineering",
        semester:'First',
        from:"Gurugram",
    },
    {   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
    name:"Naresh",
    branch:"Computer Science and Engineering",
    semester:'First',
    from:"Gurugram",
},
    
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
{   img:'https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg',
name:"Naresh",
branch:"Computer Science and Engineering",
semester:'First',
from:"Gurugram",
},
        ]

export default data;